// Text written by the Mag renderer, selected from the page URL language.
export const MAG_TEXT = {
  "zh": {
    "or": "或",
    "initial": "初始形态",
    "class": "职业",
    "stage1": "一阶 · 只看职业",
    "note1": "进化结果<b>仅</b>取决于把 Mag 喂到 Lv.10 的角色职业，与属性完全无关。",
    "gate35": "达到 Lv.35 · 比较 {stats} 最大值",
    "stage2": "二阶 · 看一阶形态 + 最高属性",
    "note2": "此处<b>与职业无关</b>：由 {first} 出发，只比最高属性。若最高属性并列，则按一阶形态的优先属性裁决 —— {name} 认 {stat}，进化为 {result}。",
    "funnel": "<strong>Lv.50 起，进化结果只取决于 Section ID 与属性排序，与二阶形态无关。</strong>\n      注意这个不对称：Lv.35 是要看一阶形态的（所以上面那根箭头有意义），Lv.50 不看二阶形态。\n      因此下方与上方之间没有连线 —— 这样的映射并不存在，并非疏漏。",
    "special": "不分 Section ID，优先于下方分支",
    "groupA": "A 组",
    "groupB": "B 组",
    "conditions": "进化条件",
    "stage3": "三阶 · 看 Section ID + 进化条件",
    "note3": "中间列是进化条件（属性比较），左右是 A 组 / B 组满足该条件时得到的 mag —— 同一条件在两组给出不同结果。<b>Lv.50 之后每 5 级还可再次进化</b>（55、60、65…），前提是满足另一组进化条件，例如把 Mag 转给另一个角色去喂。",
    "male": "男性角色",
    "female": "女性角色",
    "formula": "数值公式 + Section ID",
    "stage4": "四阶 · 看数值公式 + Section ID + 性别",
    "note4": "Lv.100 起每逢 10 的倍数判定一次（110、120…）：公式、Section ID 与角色性别必须同时满足，且<b>只能由三阶 Mag 进化</b>。四阶不保证达成 —— 若过了 100 级仍未进化，可转给条件吻合的角色再喂一次。<b>一旦进化为四阶，便不再进化，也不再学习新的 PB。</b>",
    "exclusive": "E 服独占",
    "colour": "Mag 颜色",
    "original": "原色",
    "reset": "原始（无色）",
    "colours": {
      "Red": "Red",
      "Blue": "Blue",
      "Yellow": "Yellow",
      "Green": "Green",
      "Purple": "Purple",
      "Black": "Black",
      "White": "White",
      "Cyan": "Cyan",
      "Brown": "Brown",
      "Orange": "Orange",
      "Slate Blue": "Slate Blue",
      "Olive": "Olive",
      "Turquoise": "Turquoise",
      "Fuchsia": "Fuchsia",
      "Gray": "Gray",
      "Cream": "Cream",
      "Pink": "Pink",
      "Dark Green": "Dark Green",
      "Chartreuse": "Chartreuse",
      "Azure": "Azure",
      "Royal Purple": "Royal Purple",
      "Ruby": "Ruby",
      "Sapphire": "Sapphire",
      "Emerald": "Emerald",
      "Gold": "Gold",
      "Silver": "Silver",
      "Bronze": "Bronze",
      "Plum": "Plum",
      "Violet": "Violet",
      "Goldenrod": "Goldenrod"
    },
    "effects": {
      "Invincibility": "无敌",
      "Resta": "圣泉术",
      "S&D": "强攻·强体"
    },
    "pbs": {
      "Golla": "角鹿",
      "Pilla": "神像",
      "Estlla": "海豚",
      "Farlla": "海蛇",
      "Leilla": "女神",
      "Mylla & Youlla": "双子"
    },
    "conditionLabels": {
      "HU 职业": "HU 职业",
      "RA 职业": "RA 职业",
      "FO 职业": "FO 职业",
      "POW 最大": "POW 最大",
      "DEX 最大": "DEX 最大",
      "MIND 最大": "MIND 最大"
    }
  },
  "en": {
    "or": "or",
    "initial": "Initial form",
    "class": "class",
    "stage1": "Stage 1 · class only",
    "note1": "Evolution depends <b>only</b> on the class of the character who feeds the Mag to Lv.10, regardless of stats.",
    "gate35": "Reach Lv.35 · compare the highest of {stats}",
    "stage2": "Stage 2 · first form + highest stat",
    "note2": "The class <b>does not matter here</b>: starting from {first}, only the highest stat is compared. Ties use the first form’s priority stat: {name} favours {stat}, evolving into {result}.",
    "funnel": "<strong>From Lv.50, evolution depends only on Section ID and stat order, regardless of the second form.</strong> Unlike Lv.35, which uses the first form (hence the arrow above), Lv.50 ignores the second form. No line connects the charts above and below because no such mapping exists.",
    "special": "regardless of Section ID; takes priority over the branches below",
    "groupA": "Group A",
    "groupB": "Group B",
    "conditions": "Evolution conditions",
    "stage3": "Stage 3 · Section ID + evolution conditions",
    "note3": "The middle column shows evolution conditions (stat comparisons). Left and right show the Mag obtained by Group A / B under those conditions; the same condition gives different results for each group. <b>After Lv.50, evolution can occur again every 5 levels</b> (55, 60, 65…), if another evolution condition is met, for example by giving the Mag to another character to feed.",
    "male": "Male character",
    "female": "Female character",
    "formula": "Stat equation + Section ID",
    "stage4": "Stage 4 · stat equation + Section ID + sex",
    "note4": "From Lv.100, checks occur at multiples of 10 (110, 120…). The equation, Section ID and character sex must all match, and <b>only a third-stage Mag can evolve</b>. Stage 4 is not guaranteed: if the Mag has not evolved after level 100, transfer it to a character who meets the conditions and feed it again. <b>Once it reaches stage 4, it no longer evolves or learns new PBs.</b>",
    "exclusive": "Ephinea exclusive",
    "colour": "Mag colour",
    "original": "Original",
    "reset": "Original (no tint)",
    "colours": {
      "Red": "Red",
      "Blue": "Blue",
      "Yellow": "Yellow",
      "Green": "Green",
      "Purple": "Purple",
      "Black": "Black",
      "White": "White",
      "Cyan": "Cyan",
      "Brown": "Brown",
      "Orange": "Orange",
      "Slate Blue": "Slate Blue",
      "Olive": "Olive",
      "Turquoise": "Turquoise",
      "Fuchsia": "Fuchsia",
      "Gray": "Gray",
      "Cream": "Cream",
      "Pink": "Pink",
      "Dark Green": "Dark Green",
      "Chartreuse": "Chartreuse",
      "Azure": "Azure",
      "Royal Purple": "Royal Purple",
      "Ruby": "Ruby",
      "Sapphire": "Sapphire",
      "Emerald": "Emerald",
      "Gold": "Gold",
      "Silver": "Silver",
      "Bronze": "Bronze",
      "Plum": "Plum",
      "Violet": "Violet",
      "Goldenrod": "Goldenrod"
    },
    "effects": {
      "Invincibility": "Invincibility",
      "Resta": "Resta",
      "S&D": "Shifta & Deband"
    },
    "pbs": {
      "Golla": "Golla",
      "Pilla": "Pilla",
      "Estlla": "Estlla",
      "Farlla": "Farlla",
      "Leilla": "Leilla",
      "Mylla & Youlla": "Mylla & Youlla"
    },
    "conditionLabels": {
      "HU 职业": "HU class",
      "RA 职业": "RA class",
      "FO 职业": "FO class",
      "POW 最大": "POW highest",
      "DEX 最大": "DEX highest",
      "MIND 最大": "MIND highest"
    }
  },
  "ja": {
    "or": "または",
    "initial": "初期形態",
    "class": "クラス",
    "stage1": "第1段階・クラスのみ",
    "note1": "進化先はマグをLv10にしたキャラクターのクラス<b>だけ</b>で決まり、能力値は関係ありません。",
    "gate35": "Lv35到達・{stats}の最大値を比較",
    "stage2": "第2段階・第1段階の形態＋最高能力値",
    "note2": "ここでは<b>クラスは関係ありません</b>。{first}から最高能力値だけで判定します。同率の場合は第1段階の優先能力を使います。{name}は{stat}を優先し、{result}に進化します。",
    "funnel": "<strong>Lv50以降の進化はセクションIDと能力値の大小関係だけで決まり、第2段階の形態は関係ありません。</strong>Lv35では第1段階の形態を参照するため上に矢印がありますが、Lv50では第2段階の形態を参照しません。上下の図を結ぶ線がないのは、この対応関係が存在しないためです。",
    "special": "セクションID不問・下の分岐より優先",
    "groupA": "Aグループ",
    "groupB": "Bグループ",
    "conditions": "進化条件",
    "stage3": "第3段階・セクションID＋進化条件",
    "note3": "中央列は能力値を比較する進化条件、左右はA・Bグループで得られるマグです。同じ条件でもグループによって進化先が異なります。<b>Lv50以降は5レベルごと（55・60・65…）に再進化できます</b>。別のキャラクターに渡して餌を与えるなど、別の進化条件を満たす必要があります。",
    "male": "男性キャラクター",
    "female": "女性キャラクター",
    "formula": "能力値の式＋セクションID",
    "stage4": "第4段階・能力値の式＋セクションID＋性別",
    "note4": "Lv100から10の倍数（110・120…）で判定します。能力値の式・セクションID・性別をすべて満たし、<b>第3段階のマグであること</b>が必要です。必ず第4段階になるわけではありません。Lv100を超えても進化しない場合は、条件に合うキャラクターに渡して再度餌を与えられます。<b>第4段階になると、それ以上進化せず、新しいPBも覚えません。</b>",
    "exclusive": "Ephinea限定",
    "colour": "マグカラー",
    "original": "元の色",
    "reset": "元の色（着色なし）",
    "colours": {
      "Red": "レッド",
      "Blue": "ブルー",
      "Yellow": "イエロー",
      "Green": "グリーン",
      "Purple": "パープル",
      "Black": "ブラック",
      "White": "ホワイト",
      "Cyan": "シアン",
      "Brown": "ブラウン",
      "Orange": "オレンジ",
      "Slate Blue": "スレートブルー",
      "Olive": "オリーブ",
      "Turquoise": "ターコイズ",
      "Fuchsia": "フクシア",
      "Gray": "グレー",
      "Cream": "クリーム",
      "Pink": "ピンク",
      "Dark Green": "ダークグリーン",
      "Chartreuse": "シャルトリューズ",
      "Azure": "アジュール",
      "Royal Purple": "ロイヤルパープル",
      "Ruby": "ルビー",
      "Sapphire": "サファイア",
      "Emerald": "エメラルド",
      "Gold": "ゴールド",
      "Silver": "シルバー",
      "Bronze": "ブロンズ",
      "Plum": "プラム",
      "Violet": "バイオレット",
      "Goldenrod": "ゴールデンロッド"
    },
    "effects": {
      "Invincibility": "無敵",
      "Resta": "レスタ",
      "S&D": "シフタ・デバンド"
    },
    "pbs": {
      "Golla": "ゴウラ",
      "Pilla": "パイラ",
      "Estlla": "エストラ",
      "Farlla": "ファーラ",
      "Leilla": "レイラ",
      "Mylla & Youlla": "マイラ＆ユウラ"
    },
    "conditionLabels": {
      "HU 职业": "HUクラス",
      "RA 职业": "RAクラス",
      "FO 职业": "FOクラス",
      "POW 最大": "POW最大",
      "DEX 最大": "DEX最大",
      "MIND 最大": "MIND最大"
    }
  }
};
