export const CHARTABLE_TEXT = {
  "zh": {
    "backHome": "← 返回首页",
    "title": "全等级人物能力表",
    "description": "PSOBB 全等级人物能力表",
    "loadError": "能力数据暂时未能加载，请检查网络后重试。",
    "retry": "重新加载",
    "choose": "选择职业",
    "intro": "切换职业，查看 1–200 级能力值",
    "class": "职业",
    "jumpLevel": "定位等级",
    "jump": "定位",
    "quick": "常用等级",
    "shown": "已定位 Lv. ",
    "compare": " · 切换职业可比较同等级能力值",
    "hint": "输入等级或选择常用等级，快速定位对应行",
    "count": "200 个等级",
    "scroll": "在表格内滚动查看全部等级；窄屏可左右滑动查看属性。",
    "table": " 全等级能力表",
    "caption": "1–200 级能力值",
    "level": "等级",
    "atp": "攻击力",
    "dfp": "防御力",
    "mst": "精神力",
    "ata": "命中",
    "evp": "回避力",
    "lck": "运气",
    "error": "请输入 1–200 之间的整数等级",
    "hunter": "战士 Hunter",
    "ranger": "游骑兵 Ranger",
    "force": "法师 Force"
  },
  "en": {
    "backHome": "← Back to home",
    "title": "Character stats by level",
    "description": "PSOBB character stats for levels 1–200.",
    "loadError": "Stat data could not be loaded. Check your connection and try again.",
    "retry": "Reload",
    "choose": "Choose a class",
    "intro": "Switch classes to view stats at levels 1–200",
    "class": "Class",
    "jumpLevel": "Jump to level",
    "jump": "Go",
    "quick": "Quick levels",
    "shown": "Showing Lv. ",
    "compare": " · Switch classes to compare stats at this level",
    "hint": "Enter a level or choose a quick level to jump to its row",
    "count": "200 levels",
    "scroll": "Scroll within the table to see every level; on narrow screens, scroll horizontally to see all stats.",
    "table": " stats at every level",
    "caption": "stats at levels 1–200",
    "level": "Level",
    "atp": "Attack",
    "dfp": "Defence",
    "mst": "Mental strength",
    "ata": "Accuracy",
    "evp": "Evasion",
    "lck": "Luck",
    "error": "Enter a whole-number level from 1 to 200",
    "hunter": "Hunter",
    "ranger": "Ranger",
    "force": "Force"
  },
  "ja": {
    "backHome": "← ホームに戻る",
    "title": "レベル別キャラクター能力表",
    "description": "PSOBB全クラスのLv1〜200の能力値。",
    "loadError": "能力データを読み込めませんでした。接続を確認して再試行してください。",
    "retry": "再読み込み",
    "choose": "クラスを選択",
    "intro": "クラスを切り替えてLv1〜200の能力値を確認できます",
    "class": "クラス",
    "jumpLevel": "レベルを指定",
    "jump": "移動",
    "quick": "よく使うレベル",
    "shown": "表示中：Lv",
    "compare": "・クラスを切り替えると同レベルの能力を比較できます",
    "hint": "レベルを入力するか選択すると、該当する行に移動します",
    "count": "全200レベル",
    "scroll": "表内をスクロールして全レベルを確認できます。狭い画面では横にスクロールして各能力を確認できます。",
    "table": "の全レベル能力表",
    "caption": "Lv1〜200の能力値",
    "level": "レベル",
    "atp": "攻撃力",
    "dfp": "防御力",
    "mst": "精神力",
    "ata": "命中力",
    "evp": "回避力",
    "lck": "運",
    "error": "1〜200の整数を入力してください",
    "hunter": "ハンター",
    "ranger": "レンジャー",
    "force": "フォース"
  }
} as const;
