"""Snapshot the maintained BB drop-chart name highlights and their CSS."""
import hashlib
import json
from pathlib import Path
import runpy

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT.parent / "droptable"
rules_path = SOURCE / "tools/banner_rules.py"
style_path = SOURCE / "shared/style.css"
rules = runpy.run_path(str(rules_path))
names = {**rules["WEAPON_HIT"], **dict.fromkeys(rules["NON_WEAPONS"], 0)}
records = json.loads((ROOT / "content/item-catalog/wiki.json").read_text())["records"]
unsealed = sorted(record["title"] for record in records if "Unsealing" in record["acquisition"])
top_tier = {**dict.fromkeys(unsealed, "unsealed"), **dict.fromkeys(
    ("Dark Bridge", "Dark Flow", "Dark Meteor"), "crafted"
)}
equipment = json.loads((ROOT / "content/item-catalog/equipment-images.json").read_text())
snapshot = {
    "source": "../droptable/tools/banner_rules.py",
    "rulesSha256": hashlib.sha256(rules_path.read_bytes()).hexdigest(),
    "styleSha256": hashlib.sha256(style_path.read_bytes()).hexdigest(),
    "minimumUntekkedHit": dict(sorted(names.items())),
    "topTierItems": dict(sorted(top_tier.items())),
    "rareItems": sorted(entry["title"] for entry in equipment["toolBoxes"].values() if entry["color"] == "red"),
}
(ROOT / "content/item-catalog/banner-highlights.json").write_text(
    json.dumps(snapshot, indent=2) + "\n"
)
css = style_path.read_text()


def block(selector):
    start = css.index(selector)
    opening = css.index("{", start)
    depth = 1
    end = opening + 1
    while depth:
        depth += (css[end] == "{") - (css[end] == "}")
        end += 1
    return css[start:end].replace(".drop-cell", ".identity").replace(".banner-hit-item", ".rare-item")


selectors = [
    ".drop-cell .item-name {", ".drop-cell .ss-rare-item {",
    "@keyframes ssRareRainbow", "@media (prefers-reduced-motion: reduce)",
    ".drop-cell .banner-hit-item {",
    ".drop-cell .banner-hit-item:hover,",
]
output = "/* Generated by scripts/sync_item_highlights.py from the BB drop chart. */\n"
output += "\n\n".join(block(selector) for selector in selectors) + "\n"
(ROOT / "src/app/item-catalog/item-highlights.css").write_text(output)
print(f"Synced {len(names)} named BB highlights and drop-chart styles.")
