#!/usr/bin/env python3
"""Generate the site's item dictionary from droptable/i18n_names.json."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
from pathlib import Path


REPO = Path(__file__).resolve().parent.parent
DEFAULT_AUTHORITY = Path(
    os.environ.get(
        "DROPTABLE_I18N_AUTHORITY",
        REPO.parent / "droptable" / "i18n_names.json",
    )
)
OUTPUT = REPO / "assets" / "js" / "i18n" / "items_i18n.js"
MAG_OUTPUT = REPO / "assets" / "js" / "mag-evolution.js"
MONSTER_OUTPUT = REPO / "content" / "monster-catalog" / "names.json"


def slugify(name: str) -> str:
    """Return the stable site identifier for an English item name."""
    value = re.sub(r"[^a-z0-9]+", "_", name.casefold()).strip("_")
    return value or "item"


def load_authority(path: Path) -> dict[str, dict[str, str]]:
    """Read and validate the sole translation authority."""
    data = json.loads(path.read_text(encoding="utf-8"))
    items = data.get("items")
    if not isinstance(items, dict):
        raise ValueError(f"{path} does not contain an items object")
    for english, translations in items.items():
        if not isinstance(english, str) or not english.strip():
            raise ValueError(f"{path} contains an invalid English item name")
        if not isinstance(translations, dict):
            raise ValueError(f"{path}: {english!r} translations must be an object")
        if not translations.get("zh"):
            raise ValueError(f"{path}: {english!r} has no Chinese translation")
    return items


def build_site_dictionary(items: dict[str, dict[str, str]]) -> dict[str, dict[str, str]]:
    """Convert English-keyed authority records to deterministic site IDs."""
    result: dict[str, dict[str, str]] = {}
    for english, translations in sorted(items.items(), key=lambda pair: pair[0].casefold()):
        base = slugify(english)
        item_id = base
        suffix = 2
        while item_id in result:
            item_id = f"{base}_{suffix}"
            suffix += 1
        entry = {"en": english, "zh": translations["zh"]}
        if japanese := translations.get("ja"):
            entry["ja"] = japanese
        result[item_id] = entry
    return dict(sorted(result.items()))


def render(items: dict[str, dict[str, str]], authority_bytes: bytes) -> str:
    digest = hashlib.sha256(authority_bytes).hexdigest()
    body = json.dumps(items, ensure_ascii=False, indent=2)
    return (
        "/* GENERATED by scripts/sync_item_i18n.py from "
        f"droptable/i18n_names.json (SHA-256 {digest}).\n"
        " * Do not edit this file; i18n_names.json is the sole authority. */\n"
        f"window.ITEMS_I18N = {body};\n"
    )


def render_mag_names(source: str, items: dict[str, dict[str, str]]) -> str:
    """Refresh named Mag nodes without changing evolution rules or source metadata."""
    header, separator, body = source.partition("window.MAG_EVOLUTION = ")
    if not separator or not body.rstrip().endswith(";"):
        raise ValueError("Invalid MAG_EVOLUTION data framing")
    data = json.loads(body.rstrip()[:-1])

    def align(value):
        if isinstance(value, dict):
            if "name" in value and "zh" in value:
                name = value["name"]
                if name not in items:
                    raise ValueError(f"Missing Mag identity in authority: {name!r}")
                value["zh"] = items[name]["zh"]
            for child in value.values():
                align(child)
        elif isinstance(value, list):
            for child in value:
                align(child)

    align(data)
    return header + separator + json.dumps(data, ensure_ascii=False, indent=2) + ";\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--authority", type=Path, default=DEFAULT_AUTHORITY)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    authority_bytes = args.authority.read_bytes()
    items = load_authority(args.authority)
    outputs = {
        OUTPUT: render(build_site_dictionary(items), authority_bytes),
        MAG_OUTPUT: render_mag_names(MAG_OUTPUT.read_text(encoding="utf-8"), items),
        MONSTER_OUTPUT: json.dumps(json.loads(authority_bytes)["monsters"], ensure_ascii=False, indent=2, sort_keys=True) + "\n",
    }
    if args.check:
        stale = [path.name for path, generated in outputs.items()
                 if not path.is_file() or path.read_text(encoding="utf-8") != generated]
        if stale:
            raise SystemExit(f"{', '.join(stale)} is stale; run npm run sync:i18n")
        print("Item, monster and Mag names match droptable/i18n_names.json")
        return
    for path, generated in outputs.items():
        path.write_text(generated, encoding="utf-8")
        print(f"Wrote {path} ({generated.count(chr(10)):,} lines)")


if __name__ == "__main__":
    main()
