import { access, readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'parse5';
import vm from 'node:vm';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pageRoots = ['data', 'event', 'guide', 'tools'];
const retiredAssets = [
  'assets/js/jquery.min.js',
  'assets/js/vue.min.js',
  'assets/js/vue-multiselect.min.js',
  'assets/js/page-chrome.js',
  'assets/css/bootstrap.min.css',
  'assets/css/vue-multiselect.min.css',
  'assets/js/i18n/i18n_names.json',
  'src/app/i18n/item-translation-width.service.ts',
  'scripts/merge_item_i18n.py',
  'scripts/sync_item_i18n_from_unitxt.py',
  'scripts/scrape_wiki_ja.py',
];

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(entries.map(async (entry) => {
    const absolute = path.join(directory, entry.name);
    return entry.isDirectory() ? walk(absolute) : [absolute];
  }));
  return nested.flat();
}

function visit(node, callback) {
  callback(node);
  for (const child of node.childNodes || []) visit(child, callback);
  if (node.content) visit(node.content, callback);
}

const packageJson = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'));
const dependencies = { ...packageJson.dependencies, ...packageJson.devDependencies };
for (const name of ['jquery', 'bootstrap', 'vue', 'vue-multiselect']) {
  if (dependencies[name]) throw new Error(`Retired runtime remains in package.json: ${name}`);
}

for (const relative of retiredAssets) {
  try {
    await access(path.join(root, relative));
    throw new Error(`Retired browser asset still exists: ${relative}`);
  } catch (error) {
    if (error?.code !== 'ENOENT') throw error;
  }
}

const itemTranslationSandbox = { window: {} };
const itemTranslationSource = await readFile(
  path.join(root, 'assets/js/i18n/items_i18n.js'),
  'utf8',
);
if (!itemTranslationSource.includes('GENERATED by scripts/sync_item_i18n.py')
    || !itemTranslationSource.includes('i18n_names.json is the sole authority')) {
  throw new Error('items_i18n.js must be a generated artifact of the sole authority');
}
vm.runInNewContext(
  itemTranslationSource,
  itemTranslationSandbox,
  { filename: 'items_i18n.js', timeout: 1000 },
);
const itemIdentities = new Map();
for (const [id, item] of Object.entries(itemTranslationSandbox.window.ITEMS_I18N || {})) {
  if (!item?.en) continue;
  const identity = item.en.normalize('NFKC').replaceAll(/[‘’']/g, '-').trim();
  const duplicate = itemIdentities.get(identity);
  if (duplicate) {
    throw new Error(`Duplicate canonical item identity: ${duplicate} and ${id}`);
  }
  itemIdentities.set(identity, id);
}

const angularSources = (await walk(path.join(root, 'src', 'app')))
  .filter((file) => file.endsWith('.ts'));
for (const file of angularSources) {
  const source = await readFile(file, 'utf8');
  if (file.includes(`${path.sep}generated${path.sep}pages${path.sep}`)
      && /href=\\\"(?!\/|[a-z][a-z0-9+.-]*:)/i.test(source)) {
    throw new Error(
      `${path.relative(root, file)} contains a relative link; generated content links `
      + 'must not resolve against the application-wide base URL',
    );
  }
  const usesViewInitHook = /\b(?:AfterViewInit|ngAfterViewInit)\b/.test(source);
  const accessesDom = /\b(?:ElementRef|document|window|querySelector)\b/.test(source);
  if (usesViewInitHook && accessesDom) {
    throw new Error(
      `${path.relative(root, file)} performs work in ngAfterViewInit; `
      + 'use an Angular render callback for DOM access and hydration safety',
    );
  }
  if (!file.includes(`${path.sep}generated${path.sep}`)
      && source.includes('ViewEncapsulation.None')) {
    throw new Error(
      `${path.relative(root, file)} disables style encapsulation outside the generated-content boundary`,
    );
  }
}

const itemConsumerContracts = [
  {
    file: 'src/app/events/seasonal-event.directive.ts',
    forbidden: /\bOVERRIDES\b/,
    message: 'seasonal events must not override canonical item translations',
  },
  {
    file: 'src/app/data/volopt.directive.ts',
    forbidden: /\bzh\??\s*:/,
    message: 'Vol Opt display metadata must not contain Chinese item translations',
  },
];
for (const contract of itemConsumerContracts) {
  const source = await readFile(path.join(root, contract.file), 'utf8');
  if (!source.includes('ITEM_TRANSLATIONS')) {
    throw new Error(`${contract.file} must consume canonical ITEM_TRANSLATIONS`);
  }
  if (contract.forbidden.test(source)) {
    throw new Error(`${contract.file}: ${contract.message}`);
  }
}

const itemLookupComponent = await readFile(
  path.join(root, 'src/app/item-lookup/item-lookup.component.ts'),
  'utf8',
);
const itemLookupTemplate = await readFile(
  path.join(root, 'src/app/item-lookup/item-lookup.component.html'),
  'utf8',
);
if (!itemLookupComponent.includes('ITEM_TRANSLATIONS')
    || !itemLookupTemplate.includes('{{ item.zh }}')) {
  throw new Error('item lookup must render the generated authority through Angular binding');
}
if (itemLookupTemplate.includes('[(ngModel)]')
    || !itemLookupTemplate.includes('[ngModel]="search()"')
    || !itemLookupTemplate.includes('(ngModelChange)="search.set($event)"')) {
  throw new Error('item lookup must keep display data one-way and isolate user-input updates');
}

const canonicalItemPages = [
  'data/weapon_special_reduction.html',
  'data/enemy_weapon_hit.html',
  'data/equipment_technique_boosts.html',
  'data/gallons_roulette.html',
];
const contentGenerator = await readFile(path.join(root, 'scripts/generate_angular_content.mjs'), 'utf8');
for (const relative of canonicalItemPages) {
  const source = await readFile(path.join(root, relative), 'utf8');
  if (/\bitem-width\b|data-item-width/.test(source)) {
    throw new Error(`${relative} must preserve canonical Unitxt mixed-width text`);
  }
  if (!contentGenerator.includes(`'${relative}'`)) {
    throw new Error(`${relative} must derive displayed names from canonical item translations`);
  }
}


const equipmentTechniqueBoostsSource = await readFile(
  path.join(root, 'data/equipment_technique_boosts.html'),
  'utf8',
);
const equipmentTechniqueBoostsDocument = parse(equipmentTechniqueBoostsSource);
const equipmentTechniqueBoostRows = [];
visit(equipmentTechniqueBoostsDocument, (node) => {
  if (node.tagName === 'tr') {
    const cells = node.childNodes?.filter((child) => child.tagName === 'td') || [];
    if (cells.length === 3) equipmentTechniqueBoostRows.push(cells);
  }
});
if (equipmentTechniqueBoostRows.length !== 58
    || equipmentTechniqueBoostRows.some(([item, technique, boost]) => (
  !item.attrs?.some((attribute) => attribute.name === 'data-item-en')
  || technique.attrs?.some((attribute) => attribute.name === 'data-item-en')
  || boost.attrs?.some((attribute) => attribute.name === 'data-item-en')
))) {
  throw new Error('equipment technique boosts must identify only its 58 equipment-name cells as canonical items');
}

const volOptSource = await readFile(path.join(root, 'guide/volopt.html'), 'utf8');
const volOptItemList = volOptSource.match(/<ul data-item-translation-list>([\s\S]*?)<\/ul>/)?.[1];
if (!volOptItemList) {
  throw new Error('guide/volopt.html is missing its item-translation list contract');
}
if (/<strong(?![^>]*data-item-name)[^>]*>[^<]*[A-Za-z][^<]*[\u3400-\u9fff]/.test(volOptItemList)) {
  throw new Error('guide/volopt.html contains an unmarked hard-coded bilingual item name');
}

const angularTemplates = (await walk(path.join(root, 'src', 'app')))
  .filter((file) => file.endsWith('.html'));
for (const file of angularTemplates) {
  const source = await readFile(file, 'utf8');
  if (source.includes('$any(this)')) {
    throw new Error(`${path.relative(root, file)} bypasses strict template typing with $any(this)`);
  }
}

const htmlFiles = [
  path.join(root, 'index.html'),
  path.join(root, '404.html'),
  ...(await Promise.all(pageRoots.map((directory) => walk(path.join(root, directory))))).flat(),
].filter((file) => file.endsWith('.html') && !file.startsWith(path.join(root, 'data', 'droptable')));

const violations = [];
for (const file of htmlFiles) {
  const source = await readFile(file, 'utf8');
  const document = parse(source);
  visit(document, (node) => {
    if (node.tagName === 'script') violations.push(`${path.relative(root, file)} contains <script>`);
    for (const attribute of node.attrs || []) {
      if (/^on[a-z]+$/i.test(attribute.name)) {
        violations.push(`${path.relative(root, file)} contains ${attribute.name}`);
      }
    }
  });
}
if (violations.length) throw new Error(`HTML bypasses Angular ownership:\n${violations.join('\n')}`);

console.log(`Angular ownership verified across ${htmlFiles.length} HTML sources; retired runtimes are absent.`);
